In [6]:
#Write a function so that the columns of the output matrix are powers of the input vector.

#The order of the powers is determined by the increasing boolean argument. Specifically,
#when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

import numpy as np


def funcArray(x,n,boolVal):

    if boolVal==False:
        print(np.vander(x,n,boolVal))
        
    else:
         print(np.vander(x,n,boolVal))
        
            
# Calling function to display matrix with increasing as TRUE and FALSE
funcArray(np.arange(1,5),4,True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [8]:
#Write a function so that the columns of the output matrix are powers of the input vector.

#The order of the powers is determined by the increasing boolean argument. Specifically,when increasing is False,
#the i-th output column is the input vector raised element-wise to the power of N - i - 1.

import numpy as np


def funcArray(x,n,boolVal):

    if boolVal==False:
        print(np.vander(x,n,boolVal))
        
    else:
         print(np.vander(x,n,boolVal))
        
            
# Calling function to display matrix with increasing as TRUE and FALSE
funcArray(np.arange(1,5),4,False)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
